services:
  mongo-db:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: gharti2704/mongo-db:latest
    platform: linux/arm64
    container_name: mongo-db
    env_file:
      - env/.env.mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  mysql-db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: gharti2704/mysql-db:latest
    platform: linux/arm64
    container_name: mysql-db
    env_file:
      - env/.env.mysql
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  ms-sql-db:
    build:
      context: ./ms-sql
      dockerfile: Dockerfile
    image: gharti2704/ms-sql-db:latest
    platform: linux/arm64
    container_name: ms-sql-db
    env_file:
      - env/.env.ms-sql
    ports:
      - '1433:1433'
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mongo-data:
  mysql-data:
  mssql-data:
